#!/usr/bin/env bash
# auto_retro.sh — Automatic retrospective and knowledge沉淀 after each optimization
# Run after each optimization cycle to capture learnings

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")"
RETRO_FILE="$PROJECT_DIR/references/skill-manager/RETROSPECTIVE.md"
ANTIPATTERN_FILE="$PROJECT_DIR/references/skill-manager/OPTIMIZATION_ANTIPATTERNS.md"
TIMESTAMP=$(date "+%Y-%m-%d %H:%M")

echo "=== Auto-Retro: Capturing Learnings ==="
echo "Timestamp: $TIMESTAMP"

# Run scoring
TEXT_SCORE=$(bash "$SCRIPT_DIR/score.sh" "$PROJECT_DIR/SKILL.md" 2>/dev/null | grep "Text Score" | sed 's/.*: *//' | sed 's|/.*||' || echo "N/A")
RUNTIME_SCORE=$(bash "$SCRIPT_DIR/runtime-validate.sh" "$PROJECT_DIR/SKILL.md" 2>/dev/null | grep "RUNTIME SCORE:" | awk '{print $3}' | sed 's|/.*||' || echo "N/A")
MODE_DETECTION=$(bash "$SCRIPT_DIR/runtime-validate.sh" "$PROJECT_DIR/SKILL.md" 2>/dev/null | grep "Mode Detection Tests:" | awk '{print $4}' | sed 's/%//' || echo "N/A")

echo "Current Metrics:"
echo "  Text Score: $TEXT_SCORE"
echo "  Runtime Score: $RUNTIME_SCORE"
echo "  Mode Detection: ${MODE_DETECTION}%"

# Check if this is a significant improvement
if [[ "$TEXT_SCORE" == "N/A" || "$RUNTIME_SCORE" == "N/A" ]]; then
    echo "Skipping retro - unable to get scores"
    exit 0
fi

# Calculate variance
VARIANCE=$(echo "scale=2; $TEXT_SCORE - $RUNTIME_SCORE" | bc | sed 's/^-//')
echo "  Variance: $VARIANCE"

# Generate brief retro entry
RETRO_ENTRY="### Retro @ $TIMESTAMP

| Metric | Value |
|--------|-------|
| Text Score | $TEXT_SCORE |
| Runtime Score | $RUNTIME_SCORE |
| Variance | $VARIANCE |
| Mode Detection | ${MODE_DETECTION}% |

"

# Append to RETROSPECTIVE.md if it exists
if [[ -f "$RETRO_FILE" ]]; then
    # Find last H2 and insert before it
    LAST_H2_LINE=$(grep -n "^## " "$RETRO_FILE" 2>/dev/null | tail -1 | cut -d: -f1 || echo "")
    if [[ -n "$LAST_H2_LINE" ]]; then
        HEAD_COUNT=$((LAST_H2_LINE - 1))
        head -n "$HEAD_COUNT" "$RETRO_FILE" > "${RETRO_FILE}.tmp"
        echo "$RETRO_ENTRY" >> "${RETRO_FILE}.tmp"
        tail -n +"$LAST_H2_LINE" "$RETRO_FILE" >> "${RETRO_FILE}.tmp"
        mv "${RETRO_FILE}.tmp" "$RETRO_FILE"
        echo "Added retro entry to RETROSPECTIVE.md"
    else
        echo "$RETRO_ENTRY" >> "$RETRO_FILE"
    fi
else
    mkdir -p "$(dirname "$RETRO_FILE")"
    cat > "$RETRO_FILE" << 'RETRO_EOF'
# Optimization Retrospective

> Auto-generated by auto_retro.sh after each optimization cycle
> Captures metrics and learnings for continuous improvement

RETRO_EOF
    echo "$RETRO_ENTRY" >> "$RETRO_FILE"
    echo "Created new RETROSPECTIVE.md"
fi

# Check for anti-patterns and log if found
ANTIPATTERNS_FOUND=""

VARIANCE_CHECK=$(echo "$VARIANCE > 1.5" | bc -l 2>/dev/null || echo "0")
if [[ "$VARIANCE_CHECK" == "1" ]]; then
    ANTIPATTERNS_FOUND="High Variance: $VARIANCE"
fi

TEXT_CHECK=$(echo "$TEXT_SCORE < 8.5" | bc -l 2>/dev/null || echo "0")
if [[ "$TEXT_CHECK" == "1" ]]; then
    if [[ -n "$ANTIPATTERNS_FOUND" ]]; then
        ANTIPATTERNS_FOUND="${ANTIPATTERNS_FOUND}, Low Text: $TEXT_SCORE"
    else
        ANTIPATTERNS_FOUND="Low Text: $TEXT_SCORE"
    fi
fi

RUNTIME_CHECK=$(echo "$RUNTIME_SCORE < 8.5" | bc -l 2>/dev/null || echo "0")
if [[ "$RUNTIME_CHECK" == "1" ]]; then
    if [[ -n "$ANTIPATTERNS_FOUND" ]]; then
        ANTIPATTERNS_FOUND="${ANTIPATTERNS_FOUND}, Low Runtime: $RUNTIME_SCORE"
    else
        ANTIPATTERNS_FOUND="Low Runtime: $RUNTIME_SCORE"
    fi
fi

if [[ -n "$ANTIPATTERNS_FOUND" ]]; then
    echo "Anti-patterns detected: $ANTIPATTERNS_FOUND"
fi

echo ""
echo "=== Auto-Retro Complete ==="
echo ""
echo "Summary:"
echo "  - Metrics captured"
echo "  - Retro entry added"
echo "  - Anti-patterns checked"
echo ""
echo "Next steps:"
echo "  1. Review $RETRO_FILE for learnings"
echo "  2. Run 'git add -A && git commit' to save"
echo "  3. Continue optimization"